#!/bin/bash

desired_branch="main"
username="your_username"
email="your_email"

# Check if there is already a username and email in configuration...
# If no username or email if found, it will config it...
check_credentials() {
    if ! git config --get user.name || ! git config --get user.email; then
        git config user.name "$username"
        git config user.email "$email"
    fi
}

# Check if we are in the desired branch before adding files...
# Exit the program is we're in a different branch to prevent confusion...
check_branch() {
    if [ "$(git rev-parse --abbrev-ref HEAD)" != "$desired_branch" ]; then
        echo -e "[WARNING] Not on branch $desired_branch..."
        git branch -a
        exit 1
    fi
}

# Add the files given as arguments...
# If there is no arguments, it adds all files...
add_files() {
    if [ $# -eq 0 ]; then
        echo -e "\nNo Files specified..."
        echo -e "Adding all changes...\n"
        git add .
    else
        echo -e "\nAdding Specified files...\n"

        for file in "$@"; do
            git add "$file"
            echo -e "Added: $file\n"
        done
    fi
}

# Prompt the user for a commit message...
# Then commit the changes...
# Then push the changes...
commit_and_push() {
    git status
    read -r -p "Enter Commit Message: " commit_message
    git commit -a -m "$commit_message"
    git push origin "$desired_branch"
}

# Adds files, then commits with a autogenerated message, then pushes...
# All in a defined time interval...
# Not used, needs further investigations...
auto_push() {
    i=1
    # Continuous process...
    while true; do
        if [[ -n $(git status -s) ]]; then
            add_files "$@"
            # View new added files...
            echo -e "Status:\n"
            git status
            # Generate commit message...
            git commit -a -m "Auto Commit - $i"
            git push origin master
            # Increment commit counter...
            i=$((i + 1))
        fi
        sleep 1200
    done
}

#_________________________________________________________________________
#

main() {
    check_credentials
    check_branch
    add_files "$@"
    commit_and_push
}

main "$@"